# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- task: CmdLine@2
  inputs:
    script: |
      cd .\app\
      npm run ng serve
  
- task: CmdLine@2
  inputs:
    script: |
      cd .\e2e\
      npm run cy:verify

- task: CmdLine@2
  inputs:
    script: 'npm test'